# Site settings
title: Arte de Alejandro Alvarez Armas
description: Alejandro Alvarez Armas
keywords: Arte, Alejandro, Alvarez, Armas
author: aiwen
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
